Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -231,49 +231,29 @@ jobs:
             cat .env
             npm run build
             npm run migrations >> migrations_dump.txt      
-            cat migrations_dump.txt        
-               
-  deploy-frontend:
-    docker:
-      # Docker image here that supports AWS CLI
-      - image: amazon/aws-cli
-    steps:
-      # Checkout code from git
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here          
-            yum install tar -y
-            yum install gzip -y
-            yum install python3-pip -y
-            yum -y install curl -y
-            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
-            yum install -y nodejs
+            cat migrations_dump.txt    
             
       - run:
-          name: Get backend url
+          name: Send migration results to memstash/kvdb
           command: |
-            # your code here
-            export BACKEND_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query "Reservations[*].Instances[*].PublicIpAddress" \
-              --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "API_URL = ${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
-                        
+            # Your code here
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+              then
+                curl https://kvdb.io/3EFb4K9fiyoJYSVdprPLsi/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+              else
+                exit 1
+              fi
+            exit 1
+      # Here's where you will add some code to rollback on failure
       - run:
-          name: Deploy frontend objects
+          name: Install AWS CLI for rollback
+          when: on_fail
           command: |
-            # your code here
-            cd frontend
-            npm install
-            npm run build
-            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-            aws s3 sync dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}
-                    
+            sudo apt-get -y -qq update
+            sudo apt-get -y -qq install python3
+            sudo apt-get -qq install awscli
+      - destroy-environment            
+               
 workflows:
   default:
     jobs:
